---
output:
  pdf_document:
    fig_caption: true
    latex_engine: xelatex
    keep_tex: yes
header-includes:
   - \usepackage{booktabs}
   - \usepackage[font={small},labelfont=bf,labelsep=colon]{caption}
   - \linespread{0.82}
   - \usepackage[compact]{titlesec}
   - \usepackage{enumitem}
   - \usepackage{tikz}
   - \def\checkmark{\tikz\fill[scale=0.4](0,.35) -- (.25,0) -- (1,.7) -- (.25,.15) -- cycle;}
   - \setlist{nolistsep}
   - \titlespacing{\section}{2pt}{*0}{*0}
   - \titlespacing{\subsection}{2pt}{*0}{*0}
   - \titlespacing{\subsubsection}{2pt}{*0}{*0}
   - \setlength{\parskip}{3pt}
bibliography: references.bib
csl: national-science-foundation-grant-proposals.csl
fontsize: 11pt
mainfont: Georgia
geometry: margin=0.5in
---

<!--
   - \setlength{\parskip}{3pt}
   - \setlength{\topsep}{0pt}
   - \setlength{\partopsep}{0pt}
   - \setlength{\itemsep}{0pt}
   - \setlength{\floatsep}{0pt}
   - \setlength{\intextsep}{2pt}
   - \setlength{\abovecaptionskip}{2pt}
   - \setlength{\belowcaptionskip}{0pt}
-->


<style type="text/css">
body,
code.bash{
  font-size: 8px;
}
pre {
  font-size: 8px
}
</style>

<!-- https://grants.nih.gov/grants/ElectronicReceipt/pdf_guidelines.htm -->


```{r setup, include=FALSE}
knitr::opts_chunk$set( cache=TRUE )
```

\pagenumbering{gobble}

# 1. Introduction to the Revised Application

We would like to thank the reviewers for a careful critique, the resume and summary of
which commented positively on the "potential high significance" of the
"excellent application" as well as the “expertise [of the team] in [both] lung imaging
and software development."  We are equally grateful for the reviewers’ helpful suggestions,
all of which were incorporated in this resubmission as described below.[^1]

[^1]:  Changes to the Research Plan in response to reviewers’ concerns are identified by
vertical sidebars.


__Lack of details for hardware, data, and method descriptions (Critiques 1 and 2). __
We agree and have expanded descriptions for all elements of the project, including new
discussion concerning GPU development, and hardware platforms employed and, where applicable,
publicly available competition data for performance benchmarking.  We have also removed
"trivial" items as per reviewer suggestions.


__Lack of PET imaging (Critiques 1 and 3).__
We agree concerning the importance of PET
imaging in the lung and have now included this modality in the project, as well as a
related contribution in pulmonary blood perfusion quantification based on recent work
from our group.

__Dynamic nature of the lung environment and heterogeneity of applications/equipment
not addressed (Critiques 1 and 3).__
The unique dynamic nature of the multi-modality lung imaging environment
indeed poses significant challenges to acquiring high quality images of
the lung. Although acquisition protocols continue to improve---in part due
to precisely the kinds of image registration/processing innovations that
we propose to make available through ITK-Lung, the current
state-of-the-art is sufficient to allow effective quantitation of lung
structural and functional parameters in multi-modality studies. The
major caveat, however, is that sophisticated and extensive pre- and
post-processing of the images may be required depending on the type and
degree of distortions and artifacts introduced during acquisition.
Enabling such preprocessing is exactly one of the
major goals of this project. To achieve this objective, given the
additional complexity introduced, as noted in critique, by the
heterogeneity of applications and equipment in lung imaging, flexible
and tunable (i.e., open and programmable) tools are needed, with manifold
capabilities carefully curated to cover essential analysis and
processing tasks, all of which ideally integrated within a single
coherent toolbox---this is precisely the overall goal and deliverable of
the proposed project.

__Excessive number of external collaborators (Critiques 1 and 2).__
It was suggested that the number of proposed external collaborators is potentially excessive
and possibly redundant. We agree with this assessment and have limited the primary beta
testers to research groups at the project sites (i.e., the University of Pennsylvania and
the University of Virginia).  However, we plan to maintain the proposed relationships
with the external groups but will scale back the direct assistance to them. The use of separate, independent testing sites
will increase the value of the tools produced by ensuring that their success is not specific
to the particular source of data.  This will increase the generality of the developed resources
and thus ease dissemination to the wider community.

__Lack of novelty (Critiques 2 and 3).__  Indeed, this project does not seek to invent new
algorithms and is motivated instead by the lack of access to methods that define the
current state-of-the-art, in particular, within a comprehensive, integrated framework.
Thus, in spite of the relatively modest degree of algorithmic innovation, we believe that
significant novelty lies in the proposed "initiation of a new general toolkit focused on
lung imaging" as noted in Critique 1.

__Preexisting lung image analysis software (Critique 2).__
Already existing softwares were
mentioned as obviating factors for the proposed project. It is true that "investigators
have been assessing pulmonary images of tumors/nodules, interstitial disease, and pulmonary
embolism for decades" yet public availability of such work continues to be a critical
problem.  Specific mention was made of available software accompanying the LIDC and RIDER
lung imaging databases. However, the only software that is publicly accessible appears to
be limited to interpretation and translation of the XML files describing the nodule annotations
of those specific databases.  In contrast, the COPDGene study has given rise to the
Chest Imaging Platform software, which does not yet appear to be fully available to the
public and whose focus and scope (CT imaging primarily of COPD) are significantly more
narrow than those for this project.
Similarly, we looked at the various lung-based image processing competitions that have been
held over the years and, to the best
of our knowledge, the vast majority of proposed algorithms are not publicly available.
Critique asserts that "many of the feature indices (Table 2) already exist in generic
form in Brain packages, etc;" however, we are unaware of such availability in the major
brain packages (e.g., FSL, SPM, FreeSurfer), although we do know that a number of them exist
in the Insight Toolkit because our group developed and contributed the corresponding software.
This project would target these available features---as well as create additional ones specialized
to lung images.

__Naivety on the part of the investigators (Critique 2).__
The concern is raised regarding the necessary level of sophistication of the investigators
to fulfill the project deliverables. Based on our publication record in the lung imaging field (now
documented in the revised application), we respectfully submit that this assessment represents
a significant undervaluing of our contributions, where much of our showcased
"preliminary" software has been used in large studies. A new letter from Eric Hoffman,
an acknowledged authority in the field, attests to our group’s
reputation in lung image analysis methods and software development.  Moreover, Dr. Hoffman
has joined the project team, further strengthening feasibility of the project.

__Reduction of algorithmic scope (Critique 2).__
Concerns describing the scope of the project as being too large were raised in light of the
extensive methodological depth of the field. We agree and have revised our application to
sharpen the delineation of our contributions.

__Budget (Critique 1).__
This has been reduced as per review suggestions and includes further cuts to reflect the
more limited support of external collaborators in the revised project.





