

![ANTs core processing tools for multi-modal lung imaging studies.
Using ANTs processing tools, our team has developed several lung-specific extensions
such as ventilation-based segmentation, lung and lobe estimation, and
multi-modality pulmonary template building.  Although each of these extensions requires significant
additional development and tuning, a robust and generic software foundation ensures that
these extensions are of high quality and are readily adapted to the pulmonary image
domain.](Figs/coreANtsToolsLung.png)


### 3(c.2) __Specific Aim 1:__   To develop ITK-Lung, a set of open-source software tools for CT, PET, 1H, and 3He pulmonary computational analysis

The envisioned open-science tool set for pulmonary image analysis consists of software,
processed data to illustrate the use of the software, and the ability to evaluate and visualize user-generated
results.  With this comprehensive offering, the goal of this project is to help
the pulmonary imaging research community on a much deeper level than simply providing a
set of programs.  In order to facilitate engagement on the part of the community, we are
proposing a multi-faceted approach with ITK-Lung.  The main component will be the
core \textcolor{red}{software} tool set described in Sub-Aim 1a which would permit large-scale processing of multi-modal
pulmonary image data.  To illustrate the use of the software, allow for processing of other
public and private data sets, and provide baseline data for algorithmic comparison,
\textcolor{red}{the second
component will involve the release of} CT and 1H MRI annotated atlas libraries, corresponding templates, and
data-generating scripts as described below.
The third component will be significant extensions to the well-known ITK-SNAP software for
an enhanced user experience through a full featured graphical user interface to support
interactive \textcolor{red}{tuning of parameters and interrogation of processed} results.

__3(c.2.1) Sub-Aim 1a will expand the ITK/ANTs open-source libraries by implementing currently
unavailable lung-specific algorithms.__
Many important algorithmic categories implementing fundamental lung image analysis tasks
do not currently exist in any comprehensive, publicly available package.
This is despite the fact that new algorithms for lung image analysis are frequently reported
in the literature.   An extensive survey concentrating on the years 1999–2004 is given in
[@Sluimer:2006aa] which
covers computer-aided diagnosis of lung disease and lung cancer in CT (i.e., detection and
tracking of
pulmonary nodules) and provides an overview of the many relevant segmentation methods for
pulmonary structures. Although many algorithms existed at the time, continued technical
development has only increased the number of available algorithms.    However, despite the
continued _reporting_ of pulmonary image analysis algorithms, there is no corresponding
increase in algorithmic _availability_.  _Additionally, a key problem in the pulmonary
image analysis community is that the lack of publicly available tools translates directly
into a paucity of baseline performance standards with which researchers can compare their
own algorithms [@Tustison:2013aa].  This project constitutes a specific and overdue
response to this major deficiency in the field._


\textcolor{red}{
Toward this end, a select set of tools with a track record of good performance, spanning
the range of core functionality and designed to facilitate expansion, will serve the
pulmonary research community
as a well-vetted quantitative resource and baseline for future algorithmic development.}
Table 2 comprises \textcolor{red}{the proposed} functionality for multi-modal lung
\textcolor{red}{image} analysis that would
be incorporated into ITK-Lung in addition to further enhancements to the registration
and segmentation capabilities
described in preliminary work.
Using ANTs core tools \textcolor{red}{with lung-specific modifications,
we have produced prototypical implementations complete with preliminary documentation
and github examples for several of the proposed processing capabilitiesas described
below.}

<!--
* whole lung differentiation from the chest wall (e.g., [@De-Nunzio:2011aa;@Prasad:2008aa;@Wang:2009aa;@Rikxoort:2009aa]),
* bronchial structure extraction (e.g., [@Zheng:2007aa;@Nakamura:2008aa] and the many submissions to the recent Extraction of Airways from CT (ExACT) challenge of the 2nd International Workshop on Pulmonary Image Analysis [@Lo:2009aa]),
* vasculature segmentation (e.g., [@Agam:2005aa;@Korfiatis:2011aa]),
* lobe and/or fissure detection (e.g., [@Qi:2014aa;@Doel:2015aa]), and
* feature extraction and classification (e.g., [@Uppaluri:1999aa;@Rosas:2011aa;@DeBoer:2014aa]).

Although this list is restricted to CT image analysis, inclusion of additional techniques
specific to other modalities has additional benefit and are planned for
this project (cf Table 2).
-->


__Atlas-based lung segmentation.__  Identification of anatomical structure in lung images is often a
crucial preprocessing step for quantification of morphological features or ventilation
information from functional images.  Quantitative regional analysis typically requires the
\textcolor{red}{delineation} of lung and lobar anatomy.  Although much algorithmic research for lung
segmentation has been
reported in the CT literature [@Rikxoort:2013aa], co-opting such technologies is complicated in MRI by
issues such as RF coil inhomogeneity, presence and resolution of structural detail, and
the absence of a physically-based intensity scaling.

We recently proposed a multi-atlas approach for automatically segmenting the left and right
lungs in 1H MRI [@Tustison:2015aa].  Multi-atlas approaches to segmentation have proven highly
successful in \textcolor{red}{multiple domains} [@Wang:2012aa;@Wang:2013aa] and these methods translate readily to
the pulmonary \textcolor{red}{applications}.  Whereas many current strategies for lung image segmentation employ
low-level processing techniques based on encodable heuristics, consensus-based strategies,
in contrast, optimize the prior knowledge applied to a specific segmentation problem (cf Figure 2).
The evaluation of our proposed method [@Tustison:2015aa] demonstrated excellent performance
with Jaccard overlap measures for the left and right lungs measuring $0.966\pm0.018$ and
$0.970\pm0.016$, respectively.  Further work for this project includes extension to
CT datasets with a particular emphasis on segmentation in the presence of lung pathology that
will incorporate the data from the proposed multi-atlas CT library.  Regional quantification of
pathologies indicated by ground glass opacity can be quantified from intensity-based
Bayesian segmentation with a Markov random field spatial priors (described below) following
atlas-based lung segmentation.

\input{algorithm_table.tex}

<!--
![Sample lung and lobe estimation results in both 1H MRI and CT using our
atlas-based strategy.  (Left) Lung segmentation and lobe estimation results for the given
1H MRI.  Although lobe estimation is dependent solely on the warped atlases, we are
able to obtain accurate estimates of lobes which are useful for more regional analysis
and provide a more intuitive and universal subdivision of the lungs than previous partitioning
schemes.  (Right) The utility of this method extends to CT where the integrity of lobar anatomical
markers (such as the lack of fissures illustrated by the red arrows) have been compromised due to
disease.](Figs/lungEstimation.png)
-->

__Atlas-based lobe estimation.__  For regional investigation of certain lung pathologies and
conditions, it is often useful to quantify measurements of interest within more localized
regions, such as the lobes.  However there is little (if any) usable information in 1H
MRI for image-based lobar segmentation which has led to alternative geometric subdivisions
which are ad hoc, non-anatomical, and do not adequately address intra- and inter-subject
correspondences.  \textcolor{red}{Nevertheless}, we can take advantage of
inter-subject similarities in lobar geometry to provide a prior-based estimation of
lobar divisions using a consensus labeling approach (cf Figure 2).
Specifically, to generate the lobe segmentation in a target 1H or CT lung image, we register the
same-modality atlas set to the target image (given the general increased robustness
of intra-modality vs. inter-modality image registration) using the B-spline
SyN registration approach described earlier [@Tustison:2013ac].
Subsequently, we warp the set of lobe label images to the target image using
the  atlas-to-target  transformation.  This process will be illustrated publicly as part
of the project using the open-data multi-atlas CT and 1H atlas libraries created as part of Sub-Aim 1b.
Since we have no intensity information inside
the target lung mask and CT atlas lung masks, we use a simply majority voting strategy to
generate the optimal labeling for the target image.  Following the majority voting, we
remove any labelings outside the lung mask and assign any unlabeled voxels with the label
closest in distance to that voxel.  \textcolor{red}{Additional details can be found} in
[@Tustison:2015aa] where we showed that lobar overlap measures in 1H MRI were on par
with \textcolor{red}{methods for CT images  in which}  fissure information is actually visible
(left upper: $0.882 \pm 0.059$, left lower: $0.868 \pm 0.06$, right upper: $0.852 \pm 0.067$,
right middle: $0.657 \pm 0.130$, right lower: $0.873 \pm 0.063$).  We will extend this
framework to pulmonary CT in providing
spatial prior probability maps derived from
 image-specific CT data features such as fissures, airways, and blood vessels
for data-driven, subject-specific lobe segmentation [@Doel:2015aa].


__Ventilation quantification.__
\textcolor{red}{The ability to classify} areas of varying degrees of ventilation
\textcolor{red}{represents a basic need in} pulmonary functional analysis.  In [@Tustison:2011aa], we presented
an automated algorithmic pipeline for ventilation-based partitioning of the lungs in hyperpolarized
3He and 129Xe MRI.  \textcolor{red}{Given a whole lung mask (see }
__Atlas-based lung segmentation__
\textcolor{red}{The original pipeline performs MR inhomogeneity correction followed by
Bayesian segmentation with an MRF prior.}
Without ground truth data for evaluation, we used a consensus labeling approach [@Warfield:2004aa]
to simultaneously estimate the true segmentation from given "raters"
\textcolor{red}{and the performance of those raters with respect to that estimation}.
In this evaluation, "raters" refers to the segmentation from our automated approach
and the manual tracings of three trained individuals.  In terms of combined specificity and sensitivity, our automated algorithm
demonstrated superior performance with the added benefit of being reproducible and less
time-consuming.  \textcolor{red}{Future enhancements to this pipeline will include the incoproration
of 1) an iterative bias-correction/segmentation scheme that should yield improved
optimization solutions and 2) a better performing denoising protocol based on the patch-based
method} described in [@Manjon:2010aa].

<!--
![Pulmonary functional segmentation using the algorithmic framework first described in [@Tustison:2011aa]
for hyperpolarized 3He MRI.  These data were taken from a current study looking at the
implications in ventilation pre- and post-albuterol intake including an additional
acquisition at some delay period following the post-albuterol imaging.  The
ventilation-based segmentation is as follows:  red = no ventilation, green = poorly
ventilated, blue = normally ventilated, and yellow = well-ventilated.
Note the improvement in both the qualitative assessment of the ventilation map (top) and the corresponding
segmentation time course (bottom) followed by an approximate return to pre-albuterol
conditions following the delay period.](Figs/prePostAlbuterol.png)
-->

<!--
Crucial to the development of ITK-Lung will be domain-specific experience.  For example,
although ANTs performance in brain
registration has been independently evaluated and found to be of relatively high quality
[@Klein:2009aa], tailoring our registration tool to achieve top performance levels for the
EMPIRE10 challenge (Evaluation of Methods
for Pulmonary Image REgistration 2010) required significant empirically-based tuning.  In
addition, new innovations in diffeomorphic registration technology has led to a Symmetric
Normalization B-spline variant which has demonstrated accurate normalizations
[@Tustison:2013ac]
and transformations which are particularly well-suited for pulmonary data [@Tustison:2012aa].
-->

__Multi-modality lung template construction.__
Because the template construction algorithm described in [@Avants:2010aa]
\textcolor{red}{was
originally developed for proton MRI and neuroimaging applications, it will be
modified in this project to additionally admit CT and PET data and further
adapted for specialized use in studies of the lung.
The latter development will build on our recent} innovations in diffeomorphic
registration technology that has led to a Symmetric
Normalization B-spline variant which will be extended and refined
to include patch-based similarity metrics suitable for minimizing the
computational footprint of
\textcolor{red}{problems involving very large images of the kind commonly
encountered in lung studies while at the same time}
providing accurate
normalizations [@Tustison:2013ac] for pulmonary data [@Tustison:2012aa].

<!--
In Figure 3, we illustrate the major processing components of a recent study
analyzing local changes based on a pulmonary treatment plan [@Tustison:2013ad].  This
study employed several of the tools we are proposing for inclusion in the specified aims.
The first major component is the construction of a single-subject 3He/1H MRI
template for all five imaging time points.  This step generates the statistical coordinate
system for the voxelwise regression analysis of the normalized intensities to determine
correlation with expected treatment effects.

![Voxelwise regression analysis to determine image-based response to treatment.  First,
a multi-modal, single-subject template is created to bring all time point images to
the same coordinate system.  4-D segmentation is performed on the longitudinal time series
of 3-D image volumes.  Treatment
effects are expected to follow the simplified treatment hypothesis illustrated with the
dashed blue line in the plot on the right.  To explore how the longitudinal change in expected
ventilation follows this treatment hypothesis with image data, we smooth the aligned expected
ventilation maps (to account for potential voxelwise misalignments) and then quantify how the
voxelwise intensities regress with the simplified treatment hypothesis.  This quantification
is visualized using the correlation maps depicted in the template space (top right).  Positive
correlations with the expected treatment effect are rendered in orange whereas negative correlations
are rendered in blue.](Figs/longitudinalStudy.png)
-->

__Feature indices.__  Imaging biomarkers for characterizing emphysema in CT have
have been well researched, although there are ample opportunities to refine these methods
as well as to introduce more advanced approaches.  Examples of the latter include texture
analysis for identifying the centrilobular and groundglass opacities and fractal and
connectivity approaches to differentiate centrilobular from panlobular emphysema. The
available indices for CT image analysis can roughly be divided into those that characterize the
pulmonary parenchyma:
  volumetric tissue (e.g., [@Coxson:1999aa;@Perez:2005aa]),
   distribution of low attenuation areas (LAA) (e.g., [@Coxson:2005aa;@Stolk:2007aa]),
   cooccurrence and run-length matrix features (e.g., [@Uppaluri:1999aa;@Xu:2006aa]),
   attenuation statistics (e.g., [@Gevenois:1996aa;@Hoffman:2006aa]),
   deformation measures (e.g., [@Gee:2003aa;@Sundaram:2005aa]), and
   stochastic fractal dimension features (e.g., [@Uppaluri:1999aa;@Hoffman:2006aa]);
and those that characterize the airways (e.g., [@Aykac:2003aa;@Park:1998aa;@Ederle:2003aa]).
The former are important
for subjects with an emphysematous component of disease, whereas the latter are important
for subjects with a bronchitic diseases. _\textcolor{red}{An important benefit of this
project's multi-modality scope}
 is that many of these measurements can also be directly applied to discriminative
analysis using 3He MRI \textcolor{red}{and PET} for a variety of lung diseases._
These indices can also be studied not only at any particular single time point, but also
for changes with time.

<!--
The addition of quantitative morphologic measurements of the airways
provides an assessment of the contribution of airway changes to chronic lung disease.
-->

<!--
Table 2 provides an overview of these types of
discriminative measurements, many of which can be used for CT and 3He lung assessment.
We have already implemented many of these image features and have contributed the result of our work to
the Insight Toolkit (e.g., [@Tustison:2008aa;@Tustison:2009aa]).

\input{ct_table.tex}
-->

<!--
As an
open-source repository for medical image analysis algorithms, contribution of our work
to the ITK allows researchers full access to the latest image analysis algorithms in
addition to avoiding research redundancy. It is also beneficial in that the entire ITK
community participates in the vetting of the software library.
-->

__Airway segmentation.__  \textcolor{red}{Lung} airway morphology has been previously utilized as a biomarker
for disease characterization but there are many other potential uses motivating
the inclusion of airway segmentation in any pulmonary image analysis toolkit.
In an evaluation of 15 airway segmentation algorithms [@Lo:2012aa] for the
Extraction of Airways from CT challenge held in 2009, the top 2 performers were the algorithms of [@Feuerstein:2009aa] and [@Lee:2009aa]  with the latter
being one of the more conservative algorithms and the former being more prone to false positives.
Our plan is to provide an implementation of [@Feuerstein:2009aa]  which
employs a sharpening of the airway branching edges and adaptive cuboid volumes
to \textcolor{red}{realize} a region-growing airway segmentation approach.  We \textcolor{red}{will then}
augment this
functionality with complementary aspects of our previous work [@Song:2010aa] for
removing leakage path candidates.

__\textcolor{red}{Vessel segmentation.}__
\textcolor{red}{In contrast to much of what is described in the literature, there exist
key contributions for pulmonary vessel segmentation available to the public, specifically
the algorithms described in} [@Staring:2012aa]. \textcolor{red}{Similar to much of the
research for enhancement of vessel-like morphology in different anatomies, the authors
employed Hessian-based filters for deriving a ``vesselness'' function.
Their approach ranked consistently among the top performers in the
VESSEL12 challenge organized in conjunction with the IEEE International Symposium on
Biomedical Imaging (ISBI 2012).  Given that the first author is a regular
ITK contributor, the corresponding code will be easily integrated into our platform.
}

__\textcolor{red}{Perfusion analysis.}__
\textcolor{red}{A nonparametric deconvolution technique for quantifying cerebral blood
flow was first presented in} [@Ostergaard:1996aa] \textcolor{red}{and extended for use in assessing
pulmonary blood flow} [@Ohno:2004aa;@Hansch:2012aa]\textcolor{red}{.  This deconvolution strategy was recently
implemented by our group for a separate lung imaging study but will be modified for this
project to automatically select the arterial input region and volume of interest.}

<!--
__\textcolor{red}{PET imaging.}__
-->

<!--
ITK has extensive functionality for segmentation of vessel-like structures.  Much of that
work has been incorporated into comprehensive packages such as the
analysis and visualization Vessel Modeling ToolKit (http://www.vmtk.org).  For this
project we will focus development and refinement of these
ITK capabilities for CT lung application in segmenting the pulmonary vasculature.
-->

<!--
![Potential clinical use case for identifying the feeding airway branch path to the
ventilation defect.  The functional ventilation image is normalized to the corresponding
CT image.  The airways are segmented in the individual subject space.  After identification
of the ventilation defect of interest, we can automatically determine the bronchiole
pathway from the trachea to the defect.](Figs/airways.png)
-->

<!--
__Nodule detection.__ CT is used for screening of lung cancers (i.e., pulmonary nodules)
which currently requires human intervention for the laborious and tedious task of manual
scanning.  Automated detection methods could potentially save significant time and effort which
has inspired much research literature on the topic including several commercial systems
and specialized visualization hardware for facilitating detection.  In 2009, a nodule
detection competition was held for comparing performance of individual algorithms as well
as their combinations [@Ginneken:2010aa].  This competition included entries from both
academic institutions as well as a system from Philips (although, to our knowledge, none
are available for public use).  The best performing algorithm of that competition was
based on the work presented in [@Murphy:2009aa], where a k-nearest neighbor classification employing
local image features is built from a large training data set.  We plan to implement this
method potentially with some modifications based on our experience with a more recent
challenge dealing with segmentation of pathology [@Tustison:2014aa].
-->


__\textcolor{red}{Graphics processing unit acceleration.}__
In preliminary work, we have successfully used OpenGL shader
language to perform image processing operations, such as computation
of similarity metrics between images or extraction of features from
images, on the graphics processing unit (GPU) at real-time speed. GPU
requirements for ITK-Lung will be very modest and would be met by virtually
any mid-range desktop computer sold today (e.g., a mid-range iMac).
We plan to integrate both
affine and deformable registration with GPU acceleration into ANTs.
The three components of diffeomorphic deformable registration
in ANTs that account for over 95\% of computation time are: 1)
computation of the gradient of the similarity metric
(e.g., mutual information, cross-correlation); 2) smoothing of the
gradient using Gaussian kernels; and 3) image
and vector field interpolation. All three components are highly parallelizable,
and we will write OpenGL shader
code for performing these operations on the GPU, analogous to the code currently
used for metric computation in GPU-based affine registration in ANTs.

__\textcolor{red}{Computational power.}__ With the proposed GPU acceleration of
image registration, we expect that even the most complex registration-dependent
problems will be possible to solve on a desktop computer in under 10 minutes.
\textcolor{red}{This estimate is based on} preliminary work in which we have developed
a CPU-based accelerated version of
the ANTs deformable registration algorithm that is approximately 15 times faster in
typical problems than the version currently
in use. This means that on a typical 8-core CPU, the same registration of
\textcolor{red}{$512 \times 512 \times {\sim}500$ voxel images} can be
\textcolor{red}{completed in under 20 minutes
instead of the 1-2 hours it would take on a single CPU core using the current production version of ANTs.}
This dramatic improvement was made primarily though 1)
use of more efficient metric
gradient computation algorithms, 2) use of single instruction multiple data (SIMD)
parallelization on Intel CPUs,
and 3) extensive code profiling and optimization. With the move to the GPU, we expect to
speed up registration
by another factor of 4--5 times. Therefore, the vast majority of ITK-Lung users
will not need to have access to high-performance computing clusters or other expensive hardware.

However, for power users with very large datasets or datasets that require more compute-demanding parameters
or higher-resolution registration,
we will also provide an alternative offline processing mode,
in which the registration tasks are executed on an external high-performance computing resource.
In this mode, the ITK-Lung GUI (see Sub-Aim 1c) will provide a user interface front-end to
\textcolor{red}{available processing pipelines} running remotely. It will send data to the external resource
over the network, monitor and control pipeline execution, and receive results when processing
is complete. This remote pipeline execution mode will additionally support other highly computationally
intensive tasks as well as other data processing tasks that may be added in the future.
The external resource may be either a physical Linux cluster or a virtual one
hosted on the Amazon Web Services (AWS) cloud. For AWS, we will use the MIT StarCluster
software (\url{http://star.mit.edu/cluster}) to launch a virtual cluster directly from the
ITK-Lung GUI on demand. We will take
advantage of the GPU enabled AWS instances, \textcolor{red}{which would allow} the speed-ups described above to be combined with
parallel execution across multiple hosts. The advantage of using AWS is that a power user would not need to
purchase and configure expensive hardware---they just register for an AWS account. While this would incur costs
for computational time used, these costs would be a fraction of the cost of the required hardware. For instance,
even with the most demanding datasets and parameters, \textcolor{red}{it is hard to envision a processing task that would require
more than an hour when distributed across 40 GPUs on AWS, the cost of which is currently \$26.} Data transfer to
AWS will incur negligible costs (\$0.01 per GB), particularly since data may be uploaded at  reduced resolutions
sufficient for many processing tasks.

__3(c.2.2) Sub-Aim 1b will provide two annotated multi-atlas libraries, one for CT and another for 1H MRI.__
The corresponding group templates will also be provided along with the scripts to produce the results using
ITK-Lung.  As a complement to the open-source software provided in Sub-Aim 1a, we will generate
atlas libraries for both CT and 1H MRI acquisitions.
\textcolor{red}{As indicated above, the availability of such atlases as anatomical priors
are prerequisite to application of the current state-of-the-art in robust and accurate lung
and lobe segmentation within their respective modalities.}  Additionally, the accompanying annotations provide an
open-data platform for quantitatively assessing other lung and lobe segmentation algorithms.
Both libraries will consist of $n=30$ different
subjects to represent a range of lung size and shape.  The CT atlas library will include lung, lobe,
airway, and vessel segmentations whereas the 1H MRI atlas library will include left/right lung segmentations
and lobar estimations [@Tustison:2015aa].
Along with the annotated data we will provide the scripts and documentation to allow \textcolor{red}{independent} reproduction of
the ITK-Lung results.  \textcolor{red}{Finally, optimal} group templates [@Avants:2010aa] for the two atlas
libraries
\textcolor{red}{will be generated and made openly available to be utilized as common coordinate
frameworks to support more localized (i.e., voxelwise) analyses.}

__3(c.2.3) Sub-Aim 1c will develop a graphical user interface (GUI) for running ITK-Lung on
user data and evaluating processed results.__ ANTs will be the workhorse toolkit for the
registration development effort in Aim 1, and the creation of a user-friendly GUI enabling
interactive access for the first time to ANTs functionality will be a critical innovation
toward a comprehensive registration solution for imaging studies of the lung. The existence
of the GUI will not only open ANTs to users without programming experience---which is expected
to greatly expand its already considerable user base and in turn further increase its impact
on the field---but will also significantly enhance the power of ANTs by allowing human/expert
input to interactively tune parameters and intelligently initialize as well as steer the
registration toward the solution that best satisfies both user and algorithmic constraints.
Equally important, the GUI will permit qualitative and quantitative assessment of the results
produced by ITK-Lung as well as potentially other software, another much needed capability
not currently available to the general community. \textcolor{red}{Taking}
these considerations \textcolor{red}{into account}, we propose
to base the GUI front-end to ITK-Lung on the ITK-SNAP multi-platform, open-source tool
for interactive user-guided medical image segmentation and data visualization [@Yushkevich:2006aa],
\textcolor{red}{the development of which} is led by project investigator Paul Yushkevich.
ITK-SNAP provides an effective
combination of semi-automatic segmentation functionality based on active contours
[@Caselles:1997aa, @Zhu:1996aa]
and manual delineation functionality, put together into a compact and easy-to-learn GUI,
that perfectly complements the automated segmentation functionality proposed for development
in this project. ITK-SNAP design emphasizes interaction and ease of use, with the bulk of
the development effort dedicated to the user interface. ITK- SNAP has thousands of users
(there have been over 2000 downloads per month in the last year), and our 2006 paper on
ITK-SNAP [@Yushkevich:2006aa] has been cited over 1400 times (Google Scholar) in the context of various
biomedical domains. ITK-SNAP will also be used in this project for manual labeling of the
proposed lung atlases; it is already used for this purpose by many investigators. _Most
crucially, we believe that our track record with ITK-SNAP as well as ANTs demonstrates
our team’s commitment to producing high-quality research software and making it accessible
to the wider research community through open-source practices, intuitive user interfaces,
and outreach efforts.  These strengths of the team will be applied to the software and
data developed in the course of this project._

Several features will be added to ITK-SNAP to enhance visualization and quantitation for
the registration and segmentation results of the lung-specific algorithms developed in
the project. Users will be able to edit and annotate these segmentations, modify registration
transforms, and extract quantities both globally and regionally. Transforms will be
modifiable via manual annotations (clicking corresponding landmarks, tracing curves,
and/or painting regions) or by directly modifying transform parameters. Quantitative
parameters, such as volumes and strain tensors, will be available through the ITK-SNAP
interface. Finally, existing ITK-SNAP functionality for segmentation visualization will
be \textcolor{red}{expanded} to support evaluation of registration quality, including a dashboard of performance
metrics, linked cursors identifying corresponding positions in multi-window configurations,
and fused data displays with adjustable blending. _These proposed enhancements to the software
will be extremely useful to the general imaging research community and not just those
investigators targeted in this project. Thus, the impact of this work will be both
immediate and broad on pulmonary-driven science and research._



__3(c.2.4) Software engineering.__ Both ANTs and ITK-SNAP development, based on a solid foundation
provided by the Insight Toolkit, utilizes open-source
software engineering best practices, such as the use of Git version management software
for collaborative development and easy branching and merging; use of a centralized repository
(SourceForge) for code, executable and data sharing; and use of the CMake/CTest/CDash suite for
cross-platform development, testing and automatic builds. Virtual machines with different
versions of Windows, MacOS and Linux operating systems generate nightly builds and execute
test code, uploading a binary to the central SourceForge repository. ANTs and ITK-SNAP are
documented through video and text tutorials, housed online on dedicated websites [@ANTsWebsite;@SnapWebsite].
A similar infrastructure will be developed for the software resources proposed in Aim 1.


