
# 3 Research Strategy

## __3(a) Significance__

__3(a.1) The importance of image analysis tools for research and clinical investigation.__
The increased utilization of imaging for both research and clinical purposes has
furthered
the demand for quantitative image analysis techniques.  The use of these computational
techniques is motivated by the need for less subjectivity and more standardization in
medical image interpretation, increased speed and automation in diagnosis, and greater
robustness and accuracy for determining biological correlates with imaging findings.
For example, in the area of pharmaceutical development and testing, imaging biomarkers are crucial.
In order to determine fundamental study parameters such as drug safety
and effectiveness, quantitative assessments derived from imaging measures must be objective
and reproducible [@Wang:2010aa] which is often difficult without computational aid given the intra-
and inter-reader variability in radiological practice [@Zhao:2013aa;@McErlean:2013aa].
Additionally, the exciting possibilities associated with "big data" and the potential
for improvement in individualized, evidence-based medicine has also increased the need
for sophisticated data transformation and machine learning techniques.

__3(a.2) Open-source as an essential attribute of high-impact image analysis toolkits.__
Well-vetted and publicly available software
\textcolor{red}{have transformed targeted research fields}.
For example, the neuroscience community has greatly
benefited from highly evolved software packages such as FreeSurfer [@Fischl:2012aa], the FMRIB Software
Library (FSL) [@Jenkinson:2012aa], the Analysis of Functional NeuroImages (AFNI) package [@Cox:2012aa], the
Statistical Parametric Mapping (SPM) package [@Ashburner:2012aa], and several others.

<!--
Performing a pubmed query for any one of
these softwares every year for the past decade (cf Figure 1) illustrates the growing use of
such packages and the research studies that are produced as a result.

```{r pubmedQuery, include=TRUE, echo=FALSE, warning=FALSE, message=FALSE, results="hide", fig.height=2, fig.width=6, fig.cap="Number of articles per year which cite publicly available neuroimaging analysis packages (specifically, FreeSurfer, AFNI, FSL, and SPM).  Although the benefits seem clear for the neuroscience community, analogous efforts within the pulmonary community have yet to be undertaken despite consensus amongst researchers and clinicians regarding the utility of such offerings." }
years <- 2005:2014

numberOfAbstractsPerYear <- rep( 0, length( years ) )
for( i in 1:length( years ) )
  {
  cat( "Doing year", years[i], "\n" )
  query = "afni OR fsl OR freesurfer OR (statistical AND parametric AND mapping)"
  res <- EUtilsSummary( query, db = "pubmed", retmax = 5000, mindate = as.character( years[i] ), maxdate = as.character( years[i] ) )
  summary( res )
  fetch <- EUtilsGet( res )
  abstracts <- AbstractText( fetch )
  numberOfAbstractsPerYear[i] <- length( abstracts )
  }

plotDataFrame <- data.frame( Year = as.factor( years ), NumberOfAbstracts = numberOfAbstractsPerYear )
ggplot( data = plotDataFrame, aes( x = Year, y = NumberOfAbstracts, fill = NumberOfAbstracts ) ) +
          geom_bar( stat = "identity" ) +
          scale_fill_gradient( low = "#01256e", high = "#6d0e0e" ) +
          ylab( "Number of articles" ) +
          xlab( "Publication year" ) +
          theme( legend.position = "none" )
```
-->


_\textcolor{red}{However, despite the important implications for the pulmonary imaging
community}, no such analogous set of tools exist for multi-modal pulmonary-specific research.
\textcolor{red}{Such an original software package would potentially have an immediate and
significant impact.}_  Indeed, in a recent
review of CT- and MRI-derived biomarkers for pulmonary clinical investigation, the authorial
consensus is that ``_[the absence of] universally available image analysis software'' is a major hinderance
to more widespread usage of such imaging biomarkers_ [@Hoffman:2015aa].

Medical image analysis libraries (e.g., the NIH-sponsored Insight ToolKit) provide extensive
algorithmic
capabilities for a range of generic image processing tasks.  However,
tailored software packages for certain application domains (e.g., lung image analysis)
\textcolor{red}{do not exist}
 despite the vast number of algorithms that have been proposed in the literature
\textcolor{red}{(most of which are not available to the public)}.[^1]
\textcolor{red}{Importantly}, the goals of this project would
significantly support the National Library of Medicine’s (NLM)
open-source directives in that
all software proposed in the project would be developed using the established Insight ToolKit’s coding and testing
standards with the specific objective that all project code would be contributed
for inclusion in future versions of the Insight ToolKit (ITK) as we have done in the past.
\textcolor{red}{NLM's position on open-source stems from the} documented benefits
within the targeted communities for which the \textcolor{red}{software} is developed and supported.  In addition to
the increase in research output illustrated earlier, open-source permits
\textcolor{red}{trainees} and
researchers to learn specific computational techniques in a social environment [@Yunwen:2003aa].
This, in turn, provides motivation for user-based support including potential contributions
such as bug fixes and feature additions.  Additional analyses have shown the tremendous
cost savings that open-source software yields [@Rothwell:2008aa].  Furthermore,
 open-source development and distribution within a large, and well-invested
community (such as ITK) takes advantage of Linus's law, i.e., "given enough eyeballs, all bugs are
shallow," for producing robust software.

[^1]: \textcolor{red}{Several competitions have been held in recent years focused on the processing and
analysis of lung image data (e.g., VOLCANO09---nodule detection, EMPIRE10---registration and motion estimation,
LOLA11---lung and lobe segmentation, and VESSEL12---vasculature segmentation).  To the best of our knowledge, the vast majority of
the proposed algorithms are not publicly available.  Other pulmonary imaging efforts, such as LIDC
and RIDER, have amassed large amounts of imaging data but available software support is limited to organizational
tasks specific to those databases.}

