\begin{center}
{\Large \bf ITK-Lung:  A Software Framework for Lung Image Processing and Analysis}
\end{center}

# 2 Specific Aims

<!--
One of the most significant hurdles in adopting more quantitative clinical practices and
exploring additional novel research pathways is the availability of accurate, robust, and
easy-to-use image analysis tools.
-->

Historically, the research and clinical communities (and their overlap)
have significantly benefited from computational image
analysis packages, particularly those softwares which have been tailored for
specific application domains.  Although several such established packages exist for
neuroimaging research (e.g., FSL, FreeSurfer, AFNI, SPM), _no such package exists for
pulmonary imaging analysis.  The primary goal of this project is to develop
a robust, open-source image analysis toolkit and dissemination platform
specifically targeted at the pulmonary research community.
\textcolor{red}{Given the signifcant efforts
to make lung imaging datasets publicly available (such as LIDC and RIDER), this
contribution would be extremely innovative as it would meet an obvious
need through a first-of-its-kind software package for lung image analysis.}_

<!--
The development and proliferation of quantitative image analysis methods have accelerated
research efforts and are having an increasingly significant impact in modern clinical
practice.  Although the research utility of these techniques has been amply demonstrated in
determining longitudinal and groupwise trends, they are also becoming increasingly relevant
in the clinical setting in providing biomarkers for aiding patient diagnoses, monitoring
disease progression, and determining treatment outcomes.  Increases in the capabilities
and accessibility of computational facilities and a corresponding sophistication in computational
algorithms have only made such practices more commonplace.
-->

Although methodological research is continually being presented at conferences and
published in various venues, the unfortunate reality is that much of this work exists
strictly in "advertisement" form.  Oftentimes the underlying code is unavailable to other
researchers or is implemented in a limited manner (i.e., strictly as proof-of-concept
software).  Frequently, crucial parameter choices are omitted in the corresponding
publication(s) which makes external implementations difficult.  In addition, the data used
to showcase the proposed methodologies is often limited to carefully selected snapshots
for publication purposes which might not be representative of algorithmic performance.
Finally, many of these analysis methods are patented and/or integrated into proprietary
commercial software packages which severely limits accessibility to researchers.

As a corrective alternative, this project brings together leading expertise in lung
imaging research at the \textcolor{red}{University of Pennsylvania} and
\textcolor{red}{University of Virginia} to develop, evaluate and deploy under community support
an open-source software toolkit
targeted for pulmonary imaging research.  As principal developers of the popular, open-source
ANTs, ITK-SNAP and ITK packages, we have extensive experience in the development of
well-written software and propose
to make a similar impact in the pulmonary
community with this project.  Specifically,
we plan to provide \textcolor{red}{core algorithms} for \textcolor{red}{specific} pulmonary
image analysis tasks across multiple modalities, many
of which we have \textcolor{red}{included with previous publications}.  These basic tasks
\textcolor{red}{include intra- and intermodal} pulmonary image registration,
template building for cross-sectional and longitudinal (i.e., respiratory cycle) analyses,
functional and structural lung image segmentation, \textcolor{red}{PET imaging},
\textcolor{red}{perfusion analysis}, and computation of quantitative image
indices as potential imaging biomarkers.  \textcolor{red}{These efforts would easily
integrate with related NIH-sponsored projects such as the Chest Imaging Platform}[^11]
\textcolor{red}{
which seeks to interface specific pulmonary CT algorithms (e.g., nodule detection) with the
ITK-based, open-source Slicer tool.}[^12]
In addition to the software, we will
provide scripts, documentation, and tutorial materials consistent with open-science
principles.   Formally, this project is defined by the following specific aims:

* __Specific Aim 1:__  __Develop ITK-Lung, a set of open-source software tools for CT, proton, and He-3
pulmonary computational analysis.__  These open-source software tools
\textcolor{red}{based on selected algorithms}
will specifically target pulmonary image analysis and comprise core application functions such as
inspiratory/expiratory registration, ventilation-based segmentation,
lung and lobe estimation, airway and vessel segmentation, \textcolor{red}{PET imaging},
\textcolor{red}{perfusion analysis}, and calculation of clinical indices for
characterization of lung development and pathology.  \textcolor{red}{As a complement} to these software development
efforts, CT and 1H MRI multi-atlas libraries will be provided as open data, complete
with the corresponding lung, airway, vessel, and lobe segmentations according to modality.
In addition, we will generate optimal intensity/shape templates from each library.  Both
sets of data will be provided with the scripts used to produce them in order to permit
user-reproduction of the results.
As developers of several leading open-source applications for image segmentation and registration, we
know firsthand that the impact of a particular technological innovation greatly depends on the availability
of an easily accessible software implementation.  The proposed software framework will tie together all of
the capabilities of the project’s developed methodology in the form of programmable workflows and provide
a seamless user experience through a full featured graphical user interface.  Interactive functionality
will extend beyond the ability to steer segmentation and registration pipelines to include tools for
evaluation and visualization of processed results.
* __Specific Aim 2:__  __Validate and disseminate the developed ITK-Lung resources by leveraging use
cases from a broad network of partner investigators representing the state-of-the-science in
lung imaging research.__  This aim will evaluate and refine the \textcolor{red}{proposed framework}
within the real-world context of \textcolor{red}{actual research studies with institutional and
other external collaborators with the former being the primary "beta testers."}
We will disseminate the results of the project through open-source
distribution of the software, atlases and documentation, online user support, and conduct of
hands-on training workshops.


[^11]:  http://chestimagingplatform.org

[^12]:  http:/www.slicer.org



\newpage
