---
output:
  pdf_document:
    fig_caption: true
    latex_engine: xelatex
    keep_tex: yes
header-includes:
   - \usepackage{booktabs}
   - \usepackage[font={small},labelfont=bf,labelsep=colon]{caption}
   - \linespread{0.85}
   - \usepackage[compact]{titlesec}
   - \usepackage{enumitem}
   - \usepackage{tikz}
   - \def\checkmark{\tikz\fill[scale=0.4](0,.35) -- (.25,0) -- (1,.7) -- (.25,.15) -- cycle;}
   - \setlist{nolistsep}
   - \titlespacing{\section}{2pt}{*0}{*0}
   - \titlespacing{\subsection}{2pt}{*0}{*0}
   - \titlespacing{\subsubsection}{2pt}{*0}{*0}
   - \setlength{\parskip}{3pt}
bibliography: references.bib
csl: national-science-foundation-grant-proposals.csl
fontsize: 11pt
mainfont: Georgia
geometry: margin=0.5in
---

<!--
   - \setlength{\parskip}{3pt}
   - \setlength{\topsep}{0pt}
   - \setlength{\partopsep}{0pt}
   - \setlength{\itemsep}{0pt}
   - \setlength{\floatsep}{0pt}
   - \setlength{\intextsep}{2pt}
   - \setlength{\abovecaptionskip}{2pt}
   - \setlength{\belowcaptionskip}{0pt}
-->


<style type="text/css">
body,
code.bash{
  font-size: 8px;
}
pre {
  font-size: 8px
}
</style>

<!-- https://grants.nih.gov/grants/ElectronicReceipt/pdf_guidelines.htm -->


```{r setup, include=FALSE}
knitr::opts_chunk$set( cache=TRUE )
```

\pagenumbering{gobble}

\begin{center}
{\bf Summary}
\end{center}

The advent of reproducibility and other open-science concerns have highlighted the importance of publicly available data as well as the necessary tools for processing and analysis. This is certainly the case in the neuroscience community where several publicly available software packages for imaging (e.g., SPM, FSL, AFNI, ANTs) have been heavily utilized directly resulting in significant research and progress within the field.  These packages contain essential application-specific programs for a variety of neuroimaging tasks such as brain extraction, $n$-tissue brain segmentation, and multi-atlas cortical labeling for producing discriminative biomarkers for clinical exploration (e.g., cortical thickness).  However, despite the obvious benefits that such tools have within their respective communities, there are no analogous packages for the pulmonary imaging community where relevant programs would address such functionality as lung extraction, lobe and airway segmentation, and kinematic inference via image registration.

ITK-Lung brings together leading expertise in pulmonary image analysis at Penn and the University of Virginia to develop, evaluate, and deploy a critical open-science resource under community support which would allow access to multi-modal data and tools for processing and analysis of lung data. Toward this end, a comprehensive image analysis and data package, denoted as ITK-Lung, will be developed for the pulmonary imaging community.  This first-of-its-kind package will be enhanced by data-specific tuning that will accommodate a variety of user backgrounds and needs. These developments will be evaluated through their application to real-world use cases and their practical integration with major community resources. The successful completion of this project will fully realize the value of ITK-Lung in pulmonary research and lead to an immediate and broad impact on the field.
